### ISSUE TITLE
Oni-chan, female anime style avatar

### ISSUE THREAD

**Issue by technobaboo** [omigroup/omi-chan#17]
![image](https://user-images.githubusercontent.com/4541968/152657688-5c11f23a-5ede-4eb1-bfc3-22cece4e7bce.png)
![image](https://user-images.githubusercontent.com/4541968/152657700-2b8b3115-46da-4586-b6ed-313a6a866c88.png)
![image](https://user-images.githubusercontent.com/4541968/152657703-ffaa0459-5274-4bf8-9407-9ecb67beeacc.png)

**Comment by fire** [comment]
Released under the same license as Jeana's work. CC-BY or CC0 if in doubt.

![image](https://user-images.githubusercontent.com/32321/154479017-731c36f2-b52b-45dc-9078-4de260c6c91f.png)

[SK_omi_chan_oni_chan.zip](https://github.com/omigroup/omi-chan/files/8088502/SK_omi_chan_oni_chan.zip)

Given mesh model that is unrigged and #256FES

## Noted problems.

1. forearm is out of proportion
2. head is out of proportion

## Creation notes

- https://github.com/saturday06/VRM_Addon_for_Blender/releases/tag/2_1_9 
- Create a vrm default armature template in Blender 3.0.1
- Scale equally the entire mesh to be 1.7m (female Caucasian female on the tall statistical range)
- Enable equal scaling of bones button
- Scale the arms and the neck/head
- Use autorig https://blendermarket.com/products/voxel-heat-diffuse-skinning
- Use xatlas to generate uv
- https://github.com/V-Sekai/V-Sekai-Blender-tools/tree/main/addons/blender_xatlas
- https://github.com/V-Sekai/V-Sekai-Blender-tools/tree/main/addons/Principled-Baker-master to bake uvs
- https://github.com/V-Sekai/V-Sekai-Blender-tools/tree/main/addons/corrective_smooth_baker 
- Export to vrm
- Add VRM mtoon material
- Make VRM mtoon material use black as shaded color.
- Test in 3tene and cluster.mu
- https://3d.kalidoface.com/ (first photo)
