### ISSUE TITLE
Dr. Omiga, slime robot avatar

### ISSUE THREAD

**Issue by jeanahelver** [omigroup/omi-chan#19]
![unknown](https://user-images.githubusercontent.com/32199119/152657836-e3391800-7628-4301-b059-12ec40b8f91b.png)

**Comment by technobaboo** [comment]
power cord coming out the back? :D

**Comment by technobaboo** [comment]
slime part should jiggle :3

**Comment by jeanahelver** [comment]
![unknown](https://user-images.githubusercontent.com/32199119/153722485-4d19256b-6341-4400-ac36-0ab5f9153040.png)
modelsheet
